# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cardcollection_cardplayer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardPlayer',
            new_name='CollectionPlayer',
        ),
    ]
