# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170816_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionplayer',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
