# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_pack_weight'),
        ('users', '0005_collectionplayer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcollection',
            name='players',
            field=models.ManyToManyField(blank=True, through='users.CollectionPlayer', to='players.Player'),
        ),
    ]
