# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_player_likes'),
        ('users', '0011_auto_20170817_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(blank=True, to='players.Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
