# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 19:13
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_favouriteplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteplayers',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
