# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad', name='user', field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), ), migrations.AddField(
            model_name='squad', name='web_app_import', field=models.BooleanField(
                default=False), ), migrations.AddField(
            model_name='squad', name='web_app_url', field=models.CharField(
                blank=True, max_length=100, null=True), ), ]
