# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_auto_20170916_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='slug',
        ),
        migrations.AlterField(
            model_name='squad',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
