# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 10:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_auto_20171005_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadplayer',
            name='chemistry',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
