# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0006_auto_20171007_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='large_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='short_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='squad',
            name='small_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
