# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('squads', '0008_auto_20171022_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('squad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='squads.Squad')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='squads.SquadRating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_vote', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('votes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'rating')]),
        ),
    ]
