# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0009_auto_20171025_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
