# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0007_auto_20171105_1837'),
        ('squads', '0010_squad_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='loyalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='position_changes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='sbc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sbc.SquadBuilderChallenge'),
        ),
    ]
