# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0011_auto_20171105_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='short_title',
        ),
        migrations.AlterField(
            model_name='squad',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
