# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 09:59
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20170722_1205'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('cards', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
