# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20170805_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pack_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
