# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_pack_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cached_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
