# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
