# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0007_player_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='playerrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playerrating',
            name='user_direction',
        ),
        migrations.AddField(
            model_name='playerrating',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playeruserrating',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AddField(
            model_name='playeruserrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
