# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0008_auto_20170910_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('votes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='playeruserrating',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playeruserrating',
            name='user',
        ),
        migrations.AlterField(
            model_name='playerrating',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
        migrations.AlterField(
            model_name='playerrating',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='PlayerUserRating',
        ),
        migrations.AddField(
            model_name='vote',
            name='rating',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.PlayerRating'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'rating')]),
        ),
    ]
