# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20170910_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
