# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 18:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20170914_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating_ibra',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
