# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_player_rating_ibra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rating_futily',
        ),
    ]
