# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_remove_player_rating_futily'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_perfect_chem_links',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
