# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 18:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_player_has_perfect_chem_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_team_stats', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('national_team_stats', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='ea_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ea_id_base',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
