# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_auto_20171005_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='url',
            new_name='ea_url',
        ),
    ]
