# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_auto_20171022_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pack_weight',
        ),
        migrations.AddField(
            model_name='player',
            name='pack_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
