# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_auto_20171022_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-created', 'order']},
        ),
        migrations.AddField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
