# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0002_auto_20171030_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadbuilderchallenge',
            options={'verbose_name': 'SBC Challenge', 'verbose_name_plural': 'SBC Challenges'},
        ),
        migrations.AlterModelOptions(
            name='squadbuilderchallengeaward',
            options={'verbose_name': 'SBC Award', 'verbose_name_plural': 'SBC Awards'},
        ),
        migrations.AlterModelOptions(
            name='squadbuilderchallengecategory',
            options={'ordering': ['order'], 'verbose_name': 'SBC Category', 'verbose_name_plural': 'SBC Categories'},
        ),
        migrations.AlterModelOptions(
            name='squadbuilderchallengerequirement',
            options={'verbose_name': 'SBC Requirement', 'verbose_name_plural': 'SBC Requirements'},
        ),
        migrations.AlterModelOptions(
            name='squadbuilderchallengeset',
            options={'verbose_name': 'SBC Set', 'verbose_name_plural': 'SBC Sets'},
        ),
    ]
