# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0003_auto_20171030_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadbuilderchallenge',
            name='trophy_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squadbuilderchallengeset',
            name='trophy_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
