# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0004_auto_20171101_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadbuilderchallengeset',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
