# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbc', '0006_squadbuilderchallenge_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squadbuilderchallenge',
            options={'ordering': ['title'], 'verbose_name': 'SBC Challenge', 'verbose_name_plural': 'SBC Challenges'},
        ),
        migrations.AlterModelOptions(
            name='squadbuilderchallengeset',
            options={'ordering': ['order'], 'verbose_name': 'SBC Set', 'verbose_name_plural': 'SBC Sets'},
        ),
    ]
