# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import futily.apps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packtype',
            name='roll_1_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_1_types_rating_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_1_types_rating_min',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_2_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_2_types_rating_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_2_types_rating_min',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_3_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_3_types_rating_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_3_types_rating_min',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_4_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_4_types_rating_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_4_types_rating_min',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_5_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_5_types_rating_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_5_types_rating_min',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_6_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_6_types_rating_max',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='packtype',
            name='roll_6_types_rating_min',
            field=models.PositiveIntegerField(default=75),
        ),
    ]
