# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_auto_20170815_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='ea_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='ea_pack',
            field=models.BooleanField(default=True),
        ),
    ]
