# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_auto_20170815_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='quality',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('special', 'Special')], default='special', max_length=255),
        ),
    ]
