# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_auto_20170916_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packtype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='normal_count',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_1_types',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_1_types_rating_max',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_1_types_rating_min',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_2_types',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_2_types_rating_max',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_2_types_rating_min',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_3_types',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_3_types_rating_max',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_3_types_rating_min',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_4_types',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_4_types_rating_max',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_4_types_rating_min',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_5_types',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_5_types_rating_max',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_5_types_rating_min',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_6_types',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_6_types_rating_max',
        ),
        migrations.RemoveField(
            model_name='packtype',
            name='roll_6_types_rating_min',
        ),
        migrations.AddField(
            model_name='packtype',
            name='bronze_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packtype',
            name='gold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packtype',
            name='silver_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packtype',
            name='type',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('special', 'Special')], default='special', max_length=255),
        ),
    ]
