# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_auto_20170923_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='packtype',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
