# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_auto_20170815_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='roll_1_types_count',
        ),
        migrations.RemoveField(
            model_name='type',
            name='roll_2_types_count',
        ),
        migrations.RemoveField(
            model_name='type',
            name='roll_3_types_count',
        ),
        migrations.RemoveField(
            model_name='type',
            name='roll_4_types_count',
        ),
        migrations.RemoveField(
            model_name='type',
            name='roll_5_types_count',
        ),
        migrations.RemoveField(
            model_name='type',
            name='roll_6_types_count',
        ),
        migrations.AddField(
            model_name='type',
            name='normal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='rare_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
