# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_packtype_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='packtype',
            name='show_in_list',
            field=models.BooleanField(default=False),
        ),
    ]
