# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import futily.apps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0006_auto_20170815_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='roll_1_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(choices=[('', ''), ('award_winner', 'Award winner'), ('bronze', 'Bronze'), ('confederation_champions_motm', 'Confederation champions motm'), ('fut_birthday', 'Fut birthday'), ('futties_winner', 'Futties winner'), ('gold', 'Gold'), ('gotm', 'Gotm'), ('halloween', 'Halloween'), ('imotm', 'Imotm'), ('legend', 'Legend'), ('motm', 'Motm'), ('movember', 'Movember'), ('ones_to_watch', 'Ones to watch'), ('pink', 'Pink'), ('purple', 'Purple'), ('rare_bronze', 'Rare bronze'), ('rare_gold', 'Rare gold'), ('rare_silver', 'Rare silver'), ('record_breaker', 'Record breaker'), ('sbc_base', 'Sbc base'), ('silver', 'Silver'), ('st_patricks', 'St patricks'), ('tots_bronze', 'Tots bronze'), ('tots_gold', 'Tots gold'), ('tots_silver', 'Tots silver'), ('totw_bronze', 'Totw bronze'), ('totw_gold', 'Totw gold'), ('totw_silver', 'Totw silver'), ('toty', 'Toty')], max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_2_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(choices=[('', ''), ('award_winner', 'Award winner'), ('bronze', 'Bronze'), ('confederation_champions_motm', 'Confederation champions motm'), ('fut_birthday', 'Fut birthday'), ('futties_winner', 'Futties winner'), ('gold', 'Gold'), ('gotm', 'Gotm'), ('halloween', 'Halloween'), ('imotm', 'Imotm'), ('legend', 'Legend'), ('motm', 'Motm'), ('movember', 'Movember'), ('ones_to_watch', 'Ones to watch'), ('pink', 'Pink'), ('purple', 'Purple'), ('rare_bronze', 'Rare bronze'), ('rare_gold', 'Rare gold'), ('rare_silver', 'Rare silver'), ('record_breaker', 'Record breaker'), ('sbc_base', 'Sbc base'), ('silver', 'Silver'), ('st_patricks', 'St patricks'), ('tots_bronze', 'Tots bronze'), ('tots_gold', 'Tots gold'), ('tots_silver', 'Tots silver'), ('totw_bronze', 'Totw bronze'), ('totw_gold', 'Totw gold'), ('totw_silver', 'Totw silver'), ('toty', 'Toty')], max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_3_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(choices=[('', ''), ('award_winner', 'Award winner'), ('bronze', 'Bronze'), ('confederation_champions_motm', 'Confederation champions motm'), ('fut_birthday', 'Fut birthday'), ('futties_winner', 'Futties winner'), ('gold', 'Gold'), ('gotm', 'Gotm'), ('halloween', 'Halloween'), ('imotm', 'Imotm'), ('legend', 'Legend'), ('motm', 'Motm'), ('movember', 'Movember'), ('ones_to_watch', 'Ones to watch'), ('pink', 'Pink'), ('purple', 'Purple'), ('rare_bronze', 'Rare bronze'), ('rare_gold', 'Rare gold'), ('rare_silver', 'Rare silver'), ('record_breaker', 'Record breaker'), ('sbc_base', 'Sbc base'), ('silver', 'Silver'), ('st_patricks', 'St patricks'), ('tots_bronze', 'Tots bronze'), ('tots_gold', 'Tots gold'), ('tots_silver', 'Tots silver'), ('totw_bronze', 'Totw bronze'), ('totw_gold', 'Totw gold'), ('totw_silver', 'Totw silver'), ('toty', 'Toty')], max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_4_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(choices=[('', ''), ('award_winner', 'Award winner'), ('bronze', 'Bronze'), ('confederation_champions_motm', 'Confederation champions motm'), ('fut_birthday', 'Fut birthday'), ('futties_winner', 'Futties winner'), ('gold', 'Gold'), ('gotm', 'Gotm'), ('halloween', 'Halloween'), ('imotm', 'Imotm'), ('legend', 'Legend'), ('motm', 'Motm'), ('movember', 'Movember'), ('ones_to_watch', 'Ones to watch'), ('pink', 'Pink'), ('purple', 'Purple'), ('rare_bronze', 'Rare bronze'), ('rare_gold', 'Rare gold'), ('rare_silver', 'Rare silver'), ('record_breaker', 'Record breaker'), ('sbc_base', 'Sbc base'), ('silver', 'Silver'), ('st_patricks', 'St patricks'), ('tots_bronze', 'Tots bronze'), ('tots_gold', 'Tots gold'), ('tots_silver', 'Tots silver'), ('totw_bronze', 'Totw bronze'), ('totw_gold', 'Totw gold'), ('totw_silver', 'Totw silver'), ('toty', 'Toty')], max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_5_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(choices=[('', ''), ('award_winner', 'Award winner'), ('bronze', 'Bronze'), ('confederation_champions_motm', 'Confederation champions motm'), ('fut_birthday', 'Fut birthday'), ('futties_winner', 'Futties winner'), ('gold', 'Gold'), ('gotm', 'Gotm'), ('halloween', 'Halloween'), ('imotm', 'Imotm'), ('legend', 'Legend'), ('motm', 'Motm'), ('movember', 'Movember'), ('ones_to_watch', 'Ones to watch'), ('pink', 'Pink'), ('purple', 'Purple'), ('rare_bronze', 'Rare bronze'), ('rare_gold', 'Rare gold'), ('rare_silver', 'Rare silver'), ('record_breaker', 'Record breaker'), ('sbc_base', 'Sbc base'), ('silver', 'Silver'), ('st_patricks', 'St patricks'), ('tots_bronze', 'Tots bronze'), ('tots_gold', 'Tots gold'), ('tots_silver', 'Tots silver'), ('totw_bronze', 'Totw bronze'), ('totw_gold', 'Totw gold'), ('totw_silver', 'Totw silver'), ('toty', 'Toty')], max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_6_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(choices=[('', ''), ('award_winner', 'Award winner'), ('bronze', 'Bronze'), ('confederation_champions_motm', 'Confederation champions motm'), ('fut_birthday', 'Fut birthday'), ('futties_winner', 'Futties winner'), ('gold', 'Gold'), ('gotm', 'Gotm'), ('halloween', 'Halloween'), ('imotm', 'Imotm'), ('legend', 'Legend'), ('motm', 'Motm'), ('movember', 'Movember'), ('ones_to_watch', 'Ones to watch'), ('pink', 'Pink'), ('purple', 'Purple'), ('rare_bronze', 'Rare bronze'), ('rare_gold', 'Rare gold'), ('rare_silver', 'Rare silver'), ('record_breaker', 'Record breaker'), ('sbc_base', 'Sbc base'), ('silver', 'Silver'), ('st_patricks', 'St patricks'), ('tots_bronze', 'Tots bronze'), ('tots_gold', 'Tots gold'), ('tots_silver', 'Tots silver'), ('totw_bronze', 'Totw bronze'), ('totw_gold', 'Totw gold'), ('totw_silver', 'Totw silver'), ('toty', 'Toty')], max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
    ]
