# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0007_auto_20170816_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
