# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0008_auto_20170816_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packs.Packs'),
        ),
    ]
