# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import futily.apps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0009_pack_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='roll_1_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_2_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_3_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "normal" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_4_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_5_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
        migrations.AlterField(
            model_name='type',
            name='roll_6_types',
            field=futily.apps.fields.ChoiceArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='These are part of the "rare" rolls.', size=None),
        ),
    ]
