# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='image_lg',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='image_md',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='image_sm',
        ),
    ]
