# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0002_auto_20170722_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='pack_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
