# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0003_nation_pack_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='cached_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
