# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '__first__'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsection',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='contentsection',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='contentsection',
            name='button_url',
        ),
        migrations.AddField(
            model_name='contentsection',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.Features'),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='type',
            field=models.CharField(choices=[('Adverts', [('728x90', '728x90')]), ('Content', [('features', 'Features'), ('search', 'Search'), ('special-teams', 'Special teams')])], max_length=100),
        ),
    ]
