# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_flycomment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flycomment',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
