# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0019_auto_20171022_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('pc', 'PC'), ('ps', 'Playstation'), ('xb', 'Xbox')], max_length=255)),
                ('value', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('futbin', 'Futbin'), ('futhead', 'Futhead'), ('futwiz', 'Futwiz')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
