# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 22, 22, 40, 476810, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
