# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_price_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
