# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20171111_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.IntegerField(),
        ),
    ]
