# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['-average_rating', '-total_players', 'name'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
    ]
